type User {
  id: ID!
  name: String!
  email: String!
  role: String!
}

type Query {
  users: [User]!
  user(id: ID!): User
}

type Mutation {
  createUser(input: CreateUserInput!): User! 
  updateUser(input: UpdateUserInput): User!
  deleteUser(id: ID!): User!
}

input CreateUserInput {
  name: String!
  email: String!
  password: String!
  role: String!
}

input UpdateUserInput {
  id: ID!
  name: String
  email: String
  password: String
  role: String
}
