type User {
  id: ID!
  name: String!
  email: String!
  role: String!
}

type Query {
  users: [User]! @authorized
  user(id: ID!): User @authorized
  me: User @authorized
}

type Mutation {
  createUser(input: CreateUserInput!): User! @authorized
  updateUser(input: UpdateUserInput): User! @authorized
  deleteUser(id: ID!): User! @authorized

  login(username: String!, password: String!): String! 
  refreshToken(token: String!): String! @authorized
}

input CreateUserInput {
  name: String!
  email: String!
  password: String!
  role: String!
}

input UpdateUserInput {
  id: ID!
  name: String
  email: String
  password: String
  role: String
}
